private_data_purger.settings:
  type: config_object
  label: 'Purge Settings'
  mapping:
      entities: #a sequence of object with unknown keys
        type: sequence
        label: 'Entities'
        sequence:
          type: mapping
          label: 'Entity'
          mapping:
            entity_type:
              type: string
              label: 'Entity Type'
            entity_name:
              type: string
              label: 'Used to delete the entity name '
            db_field_name:
              type: string
              label: 'the field name to delete'
            db_field_type:
              type: string
              label: "wether it's timestamp or date"
            id_column:
              type: string
              label: 'the field name to delete'



     