private_data_purger.settings:
  type: config_object
  label: 'Purge Settings'
  mapping:
      data: #a sequence of object with unknown keys
        type: sequence
        label: 'Entities'
        sequence:
          type: mapping
          label: 'Entity'
          mapping:
            entity_type:
              type: string
              label: 'Entity Type'
            entity_name:
              type: string
              label: 'Used to delete the entity name '
            field_name:
              type: string
              label: 'the field name to delete'
            field_type:
              type: string
              label: "wether it's timestamp or date"



     