private_data_purger.settings:
  type: config_object
  label: 'Purge Settings'
  mapping:
      entities: #a sequence of object with unknown keys
        type: sequence
        label: 'Entities'
        sequence:
          type: mapping
          label: 'Entity'
          mapping:
            entity_type:
              type: string
              label: 'Entity Type'
            created:
              type: string
              label: 'Purge if older than (e.g. "1 year")'



     